language: go

go:
 - 1.8

before_install:
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls

script:
  - make build
  - overalls -project=github.com/alanbover/deathnode -covermode=count
  - goveralls -coverprofile=overalls.coverprofile -service travis-ci